project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links:
    - text: Diskussion Living Document
      href: https://github.com/maehr/diskriminierungsfreie-metadaten/discussions
    - text: Quellcode
      href: https://github.com/maehr/diskriminierungsfreie-metadaten
  manuscript-url: https://maehr.github.io/diskriminierungsfreie-metadaten/

format:
  html:
    doi: 10.5281/zenodo.11124719
    date-modified: last-modified
    link-external-icon: true
    link-external-newwindow: true
    notebook-links: false
    comments:
      giscus:
        repo: maehr/diskriminierungsfreie-metadaten
    css:
      - custom.css
    include-in-header:
      - custom-header.html
    page-layout: full
    license: CC BY-SA
    
  docx:
    reference-doc: custom-reference.docx
    fig-align: left
    subject: Diskriminierungssensible Metadaten
    category: Handbuch
    toc: true
    toc-depth: 4
    toc-title: Inhaltsverzeichnis
    notebook-links: false
  pdf:
    pdf-engine: xelatex
    keep-tex: false
    notebook-links: false
