project:
  type: manuscript

manuscript:
  article: handbuch-diskriminierungsfreie-metadaten.qmd
  resources:
    - data/genderopen_gnd_mapping.csv
  code-links:
    - text: Diskussion Living Document
      href: https://github.com/maehr/diskriminierungsfreie-metadaten/discussions
    - text: Quellcode
      href: https://github.com/maehr/diskriminierungsfreie-metadaten
  manuscript-url: https://maehr.github.io/diskriminierungsfreie-metadaten/

format:
  html:
    doi: { { LATEST_DOI } }
    date-modified: last-modified
    link-external-icon: true
    link-external-newwindow: true
    comments:
      giscus:
        repo: maehr/diskriminierungsfreie-metadaten
    css:
      - custom.css
    include-in-header:
      - custom-header.html
    page-layout: full
    license: CC BY-SA
  docx:
    reference-doc: custom-reference.docx
    fig-align: left
    subject: Diskriminierungsfreie Metadaten
    category: Handbuch
    toc: true
    toc-depth: 3
    toc-title: Inhaltsverzeichnis
  pdf:
    pdf-engine: xelatex
    keep-tex: false
